# Generated by Django 4.0.4 on 2022-04-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('nome_social', models.CharField(max_length=120, verbose_name='Nome Social')),
                ('data_nascimento', models.DateField(max_length=11, verbose_name='Data de nascimento')),
                ('altura', models.DecimalField(decimal_places=5, max_digits=5, max_length=5, verbose_name='Altura')),
                ('peso', models.DecimalField(decimal_places=5, max_digits=5, max_length=5, verbose_name='Peso')),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('indefinido', 'Indefinido')], max_length=30, verbose_name='Sexo')),
                ('cor', models.CharField(choices=[('amarela', 'Amarela'), ('branca', 'Branca'), ('indigina', 'Indigina'), ('negra', 'Negra'), ('parda', 'Parda')], max_length=30, verbose_name='Cor')),
                ('identidade', models.CharField(max_length=50, verbose_name='N. Identitidade')),
                ('orgao_emissor', models.CharField(max_length=80, verbose_name='Orgão Emissor')),
                ('certidao_nascimento', models.CharField(max_length=80, verbose_name='Certidão de nascimento')),
                ('estado_civil', models.CharField(choices=[('casado', 'Casado'), ('uniao-estavel', 'Uniao estavel'), ('desquitado', 'Desquitado'), ('divorciado', 'Divorciado'), ('outros', 'Outros')], max_length=30, verbose_name='Estado Civil')),
                ('nacionalidade', models.CharField(choices=[('brasileiro', 'brasileiro'), ('estrangeiro', 'Estrangeiro'), ('outros', 'Outros')], max_length=30, verbose_name='Estado Civil')),
                ('endereço', models.CharField(max_length=80, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=50, verbose_name='Numero')),
                ('complemento', models.CharField(max_length=50, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=60, verbose_name='Bairro')),
                ('tipo_logradouro', models.CharField(choices=[('rua', 'Rua'), ('avenida', 'Avenida'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo Logradouro')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('cep', models.CharField(max_length=11, verbose_name='Cep')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('contato', models.CharField(max_length=80, verbose_name='Contato')),
                ('nome_mae', models.CharField(max_length=80, verbose_name='Nome da mãe')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
