# Generated by Django 4.0.4 on 2022-04-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='nacionalidade',
            field=models.CharField(choices=[('brasileiro', 'brasileiro'), ('estrangeiro', 'Estrangeiro'), ('outros', 'Outros')], max_length=30, verbose_name='Nacionalidadel'),
        ),
    ]
