# Generated by Django 4.0.4 on 2022-04-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_pacientes_nacionalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='altura',
            field=models.CharField(max_length=5, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='nacionalidade',
            field=models.CharField(choices=[('brasileiro', 'Brasileiro'), ('estrangeiro', 'Estrangeiro'), ('outros', 'Outros')], max_length=30, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='peso',
            field=models.CharField(max_length=5, verbose_name='Peso'),
        ),
    ]
