# Generated by Django 4.0.4 on 2022-05-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_prontuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Laudo'),
        ),
    ]
