# Generated by Django 4.0.4 on 2022-05-01 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_prontuario_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prontuario',
            old_name='paciente',
            new_name='nome',
        ),
    ]
