# Generated by Django 4.0.4 on 2022-05-01 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_rename_paciente_prontuario_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prontuario',
            options={'verbose_name': 'Prontuário', 'verbose_name_plural': 'Prontuários'},
        ),
        migrations.RenameField(
            model_name='prontuario',
            old_name='nome',
            new_name='paciente',
        ),
    ]
