# Generated by Django 4.0.4 on 2022-05-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_alter_prontuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='creatinina',
            field=models.CharField(default=False, max_length=100, verbose_name='Dosagem de Creatinina - mg/dL0,31 mg/dL a 0,92 mg/dL'),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='laudo_ecocardiograma',
            field=models.TextField(blank=True, default=True, verbose_name='Laudo ecocardiograma'),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='laudo_eletrocardiograma',
            field=models.TextField(blank=True, default=False, verbose_name='Laudo eletrocardiograma'),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='laudo_ultrassom',
            field=models.TextField(default=True, verbose_name='Laudo ultrassom'),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='obs',
            field=models.TextField(default=False, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='potacio',
            field=models.CharField(default=False, max_length=100, verbose_name='Dosagem de Potássio - mmol/L3,50 mmol/L a 5,00 mmol/L'),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='ureia',
            field=models.CharField(default=False, max_length=100, verbose_name='Dosagem de Uréia  - mg/dL 15 mg/dL a 45 mg/dL'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='descricao',
            field=models.TextField(blank=True, default=False, verbose_name='Laudo padrão'),
        ),
    ]
