# Generated by Django 4.0.4 on 2022-05-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_alter_pacientes_altura_alter_pacientes_peso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
