# Generated by Django 4.0.4 on 2022-05-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0012_alter_pacientes_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='certidao_nascimento',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='cpf',
            field=models.CharField(default='XXX.XXX.XXX-XX', max_length=80, verbose_name='CPF'),
        ),
    ]
