# Generated by Django 4.0.4 on 2022-05-03 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0014_especialidades_exames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='paciente',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientes'),
        ),
    ]
