# Generated by Django 4.0.4 on 2022-05-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_alter_prontuario_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='exames',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=8, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
