# Generated by Django 4.0.4 on 2022-05-03 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('especialidade', models.CharField(max_length=200, verbose_name='Especialidades')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Exames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo', models.CharField(max_length=80, verbose_name='Codigo')),
                ('exame', models.CharField(max_length=200, verbose_name='Exame')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('nome_social', models.CharField(max_length=120, verbose_name='Nome Social')),
                ('data_nascimento', models.DateField(max_length=11, verbose_name='Data de nascimento')),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('indefinido', 'Indefinido')], max_length=30, verbose_name='Sexo')),
                ('cor', models.CharField(choices=[('amarela', 'Amarela'), ('branca', 'Branca'), ('indigina', 'Indigina'), ('negra', 'Negra'), ('parda', 'Parda')], max_length=30, verbose_name='Cor')),
                ('identidade', models.CharField(max_length=50, verbose_name='N. Identitidade')),
                ('orgao_emissor', models.CharField(max_length=80, verbose_name='Orgão Emissor')),
                ('cpf', models.CharField(default='XXX.XXX.XXX-XX', max_length=80, verbose_name='CPF')),
                ('estado_civil', models.CharField(choices=[('casado', 'Casado'), ('uniao-estavel', 'Uniao estavel'), ('desquitado', 'Desquitado'), ('divorciado', 'Divorciado'), ('outros', 'Outros')], max_length=30, verbose_name='Estado Civil')),
                ('nacionalidade', models.CharField(choices=[('brasileiro', 'Brasileiro'), ('estrangeiro', 'Estrangeiro'), ('outros', 'Outros')], max_length=30, verbose_name='Nacionalidade')),
                ('endereco', models.CharField(max_length=80, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=50, verbose_name='Numero')),
                ('complemento', models.CharField(max_length=50, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=60, verbose_name='Bairro')),
                ('tipo_logradouro', models.CharField(choices=[('rua', 'Rua'), ('avenida', 'Avenida'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo Logradouro')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('cep', models.CharField(max_length=11, verbose_name='Cep')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('contato', models.CharField(max_length=80, verbose_name='Contato')),
                ('nome_mae', models.CharField(max_length=80, verbose_name='Nome da mãe')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Altura')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('pape', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PAPE - mmHg')),
                ('fc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='FC - bpm')),
                ('hgt', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='HGT')),
                ('creatinina', models.CharField(max_length=100, verbose_name='Dosagem de Creatinina - mg/dL0,31 mg/dL a 0,92 mg/dL')),
                ('potacio', models.CharField(max_length=100, verbose_name='Dosagem de Potássio - mmol/L3,50 mmol/L a 5,00 mmol/L')),
                ('ureia', models.CharField(max_length=100, verbose_name='Dosagem de Uréia  - mg/dL 15 mg/dL a 45 mg/dL')),
                ('anamnse', models.TextField(blank=True, verbose_name='Anamnse')),
                ('antecedentes_pessoais', models.TextField(blank=True, verbose_name='Antecedentes pessoais')),
                ('comorbidades', models.TextField(blank=True, verbose_name='Comorbidades')),
                ('medicamentos', models.TextField(blank=True, verbose_name='Medicamentos em uso')),
                ('exames_fisicos', models.TextField(blank=True, verbose_name='Exame Fisico')),
                ('conduta', models.TextField(blank=True, verbose_name='Conduta')),
                ('retorno', models.TextField(blank=True, verbose_name='Retorno')),
                ('obs', models.TextField(default=False, verbose_name='Observação')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.exames')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientes')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
            },
        ),
    ]
