# Generated by Django 4.0.4 on 2022-05-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='creatinina',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Dosagem de Creatinina - mg/dL0,31 mg/dL a 0,92 mg/dL'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='obs',
            field=models.TextField(verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='potacio',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Dosagem de Potássio - mmol/L3,50 mmol/L a 5,00 mmol/L'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='ureia',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Dosagem de Uréia  - mg/dL 15 mg/dL a 45 mg/dL'),
        ),
    ]
