# Generated by Django 4.0.4 on 2022-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_prontuario_creatinina_alter_prontuario_obs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='situacao',
            field=models.CharField(choices=[('Liberado', 'Liberado'), ('Pendente', 'Pendente'), ('Bloqueado', 'Bloqueado')], default=2, max_length=200, verbose_name='Situação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='cpf',
            field=models.CharField(blank=True, default='XXX.XXX.XXX-XX', max_length=14, verbose_name='CPF'),
        ),
    ]
