# Generated by Django 4.0.4 on 2022-05-03 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_prontuario_creatinina_alter_prontuario_obs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='epecialidade',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='pacientes.especialidades'),
            preserve_default=False,
        ),
    ]
