# Generated by Django 4.0.4 on 2022-05-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_prontuario_epecialidade'),
        ('pacientes', '0003_prontuario_situacao_alter_pacientes_cpf'),
    ]

    operations = [
    ]
