# Generated by Django 4.0.4 on 2022-05-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_merge_20220504_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='epecialidade',
        ),
    ]
