# Generated by Django 4.0.4 on 2022-05-04 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_remove_prontuario_epecialidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='anamnse',
        ),
    ]
